version: '3'
services:
  jupyter:
    build: ./
    container_name: ml-jupyter
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /work --ip=0.0.0.0
  lab:
    build: ./
    container_name: ml-lab
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /work --ip=0.0.0.0
  python:
    build: ./
    container_name: ml-python
    volumes:
      - ./:/work
    working_dir: /work
    command: python
  julia:
    build: ./
    container_name: ml-julia
    volumes:
      - ./:/work
    working_dir: /work
    command: julia
  streamlit:
    build: ./
    container_name: ml-streamlit
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8501:8501"
    command: streamlit run app.py